//
//  TransfeSceneInteractorTests.swift
//  TransactionApp
//
//  Created by Gautam Singh on 12/11/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import XCTest
@testable import TransactionApp


final class TransfeSceneInteractorTests: XCTestCase {
  
    override func setUp() {
     
    }
    
    override func tearDown() {
      
    }
}


